config/routes.rb
RedmineApp::Application.routes.draw do
  resources :functions, except: [:index, :show] do
    collection do
      match '/visibilities', to: "functions#visibilities", :via => [:get, :post]
      put '/available_functions_per_project', to: "functions#available_functions_per_project"
      put '/visible_functions_per_tracker', to: "functions#visible_functions_per_tracker"
      put '/activated_functions_per_tracker', to: "functions#activated_functions_per_tracker"
      put '/copy_functions_settings_from_project', to: "functions#copy_functions_settings_from_project"
    end
  end
  resources :functional_roles, only: [:update]  
  get 'issues/functions/:project_id(/*viewers)', :controller => 'functions', :action => 'index_issue' ,:as => 'index_issue_function'
end

app/models/function.rb
class Function < ApplicationRecord
  include Redmine::SafeAttributes

  acts_as_positioned

  safe_attributes :name, :position, :authorized_viewers, :move_to, :hidden_on_overview, :active_by_default, :see_all_issues, :description

  has_many :member_functions, :dependent => :destroy
  has_many :members, :through => :member_functions

  has_many :project_functions, :dependent => :destroy
  if Redmine::Plugin.installed?(:redmine_organizations)
    has_many :organization_functions, :dependent => :destroy
    has_many :organization_non_member_functions, :dependent => :destroy
  end
  has_many :projects, :through => :project_functions

  after_create :set_own_visibility,
               :if => Proc.new { |_| Function.column_names.include?("authorized_viewers") }

  validates_presence_of :name
  validates_length_of :name, maximum: 40

  scope :sorted, lambda { order("#{table_name}.position ASC") }
  scope :active_by_default, -> { where("active_by_default = ?", true) }
  scope :visible_on_project_overview, -> { where(hidden_on_overview: false) }

  def self.available_functions_for(project)
    functions = Function.joins(:project_functions).where("project_id = ?", project.id).sorted if project.present?
    if functions == nil || functions.blank?
      functions = Function.active_by_default.sorted
    end
    functions
  end

  def authorized_viewer_ids
    "#{authorized_viewers}".split("|").reject(&:blank?).map(&:to_i)
  end

  def to_s
    name
  end

  def allowed_to?(action)
    true # TODO Remove this method without breaking issues search
  end

  def users_by_project(project)
    User.joins(:members => :member_functions).where("function_id = ? AND project_id = ?", self.id, project.id).active.order("lastname ASC")
  end

  def users_by_project_and_organization(project, organization)
    User.joins(:members => :member_functions)
        .where("function_id = ?", self.id)
        .where("project_id = ?", project.id)
        .where("organization_id = ?", organization.id)
        .active.order("lastname ASC")
  end

  def self.functions_from_authorized_viewers(authorized_viewers)
    Function.where(:id => "#{authorized_viewers}".split("|")).sorted
  end

  def is_activated?(project:)
    project.functions.present? ? project.functions.include?(self) : self.active_by_default
  end

  def update_private_notes_group(functions_ids)
    grouped_functions = [self] | Function.where(id: functions_ids)
    grouped_functions.each do |group|
      PrivateNotesGroup.where(group_id: group.id).where("function_id NOT IN (?)", grouped_functions.map(&:id)).delete_all
      PrivateNotesGroup.where(function_id: group.id).where("group_id NOT IN (?)", grouped_functions.map(&:id)).delete_all
      (grouped_functions - [group]).each do |f|
        PrivateNotesGroup.find_or_create_by(group_id: group.id, function_id: f.id)
      end
    end
  end

  private

  def set_own_visibility
    reload
    if !authorized_viewers.present? || !authorized_viewers.split('|').include?(self.id)
      update_attribute(:authorized_viewers, "#{authorized_viewers.present? ? authorized_viewers : "|"}#{self.id}|")
    end
  end

end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
  layout 'admin'

  before_action :require_admin, :except => [:index,
                                            :available_functions_per_project,
                                            :visible_functions_per_tracker,
                                            :activated_functions_per_tracker,
                                            :index_issue
  ]
  before_action :find_function, :only => [:edit, :update, :destroy]

  def index_issue
    @project = Project.find(params[:project_id])
    @viewers = params[:viewers].present? ? params[:viewers].split(',') : []
    @functions = Function.available_functions_for(@project).sorted
    @users_by_function = @project.users_by_function if @project.present?
  end

  def new
    @function = Function.new
    @function.safe_attributes = params[:function]
    @functional_roles = Function.sorted.all
  end

  def create
    @function = Function.new
    @function.safe_attributes = params[:function]
    if request.post? && @function.save
      @function.update_private_notes_group(params[:function][:private_notes_group]) if params[:function][:private_notes_group].present?
      flash[:notice] = l(:notice_successful_create)
      redirect_to roles_path
    else
      @functional_roles = Function.sorted.all
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    @function.safe_attributes = params[:function]
    if @function.save
      @function.update_private_notes_group(params[:function][:private_notes_group]) if Redmine::Plugin.installed?(:redmine_comments)
      respond_to do |format|
        format.html {
          flash[:notice] = l(:notice_successful_update)
          redirect_to edit_function_path(@function)
        }
        format.js { head 200 }
      end
    else
      respond_to do |format|
        format.html { render :action => 'edit' }
        format.js { head 422 }
      end
    end
  end

  def destroy
    @function.destroy
    redirect_to roles_path
  rescue
    flash[:error] = l(:error_can_not_remove_role)
    redirect_to roles_path
  end

  def visibilities
    @functional_roles = Function.sorted.all
    if request.post?
      @functional_roles.each do |role|
        viewers = '|'
        viewers = "#{viewers}#{params[:visibilities][role.id.to_s].join('|')}|" if params[:visibilities][role.id.to_s].present?
        role.update_attribute(:authorized_viewers, "#{viewers}#{role.id}|")
      end
      flash[:notice] = l(:notice_successful_update)
      redirect_to roles_path
    end
  end

  def copy_functions_settings_from_project
    current_project = Project.find(params[:project_id])
    project_from = Project.find(params[:project_from])

    current_project.project_functions = []
    project_from.project_functions.each do |pf|
      new_pf = ProjectFunction.new
      new_pf.attributes = pf.attributes.dup.except("id", "project_id")
      pf.project_function_trackers.each do |pft|
        new_pft = ProjectFunctionTracker.new
        new_pft.attributes = pft.attributes.dup.except("id", "project_function_id")
        new_pf.project_function_trackers << new_pft
      end
      current_project.project_functions << new_pf
    end
    current_project.autochecked_functions_mode = project_from.autochecked_functions_mode
    current_project.save
    respond_to do |format|
      format.html { redirect_to :controller => 'projects', :action => 'settings', :id => current_project.id, :tab => 'functional_roles' }
      format.js
    end
  end

  def available_functions_per_project
    project = Project.find(params[:project_id])
    if params[:function_ids].present?
      functions = Function.where(id: params[:function_ids])
      project.functions = functions
    end
    project.autochecked_functions_mode = params[:autocheck_mode] if params[:autocheck_mode]
    project.save
    respond_to do |format|
      format.html { redirect_to :controller => 'projects', :action => 'settings', :id => project.id, :tab => 'functional_roles', nav: params[:nav] }
      format.js
    end
  end

  def visible_functions_per_tracker
    context = :visibility
    project = Project.find(params[:project_id])
    set_function_params_per_project_and_tracker(context, project, params)
    respond_to do |format|
      format.html { redirect_to :controller => 'projects', :action => 'settings', :id => project.id, :tab => 'functional_roles', nav: params[:nav] }
      format.js
    end
  end

  def activated_functions_per_tracker
    context = :autochecked
    project = Project.find(params[:project_id])
    set_function_params_per_project_and_tracker(context, project, params)
    respond_to do |format|
      format.html { redirect_to :controller => 'projects', :action => 'settings', :id => project.id, :tab => 'functional_roles', nav: params[:nav] }
      format.js
    end
  end

  private

  def find_function
    @function = Function.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def set_function_params_per_project_and_tracker(context, project, params)
    tracker_ids = project.tracker_ids
    function_ids = project.function_ids
    function_ids.each do |function_id|
      project_function = ProjectFunction.where(function_id: function_id, project_id: project.id).first

      tracker_ids.each do |tracker_id|
        if project_function.present?
          project_function_tracker = ProjectFunctionTracker.find_or_create_by(tracker_id: tracker_id, project_function_id: project_function.id)
          project_function_tracker.visible = true if project_function_tracker.visible.nil? # Set default value
          if context == :visibility
            project_function_tracker.visible = params["function_visibility"].present? && params["function_visibility"][tracker_id.to_s].present? && params["function_visibility"][tracker_id.to_s].include?(function_id.to_s)
          end
          if context == :autochecked
            project_function_tracker.checked = params["function_activation_per_tracker"].present? && params["function_activation_per_tracker"][tracker_id.to_s].present? && params["function_activation_per_tracker"][tracker_id.to_s].include?(function_id.to_s)
          end
          project_function_tracker.save
        end
      end

      if context == :autochecked && project_function.present?
        checked_functions_ids = params["function_activation_per_user_function"][function_id.to_s] || []
        project_function.authorized_viewers = '|' + checked_functions_ids.join('|') + '|'
        project_function.save
      end

    end
  end

end

app/views/functions/_form.html.erb
<%= error_messages_for 'function' %>

<div class="settings box tabular">
  <p><%= f.text_field :name, :required => true %></p>
  <p><%= f.text_field :description, size: 50 %></p>
  <p><%= f.check_box :hidden_on_overview %></p>
  <p><%= f.check_box :active_by_default %></p>
  <p><%= f.check_box :see_all_issues %></p>
</div>

<div class="visibility_tab">
  <h3><%= l(:permission_add_issues) %> / <%= l(:permission_edit_issues) %></h3>
  <div class="box tabular" id="limited_visibility">
    <fieldset>
      <legend><%= l(:text_involvement_explanation) %></legend>
      <%= render "functions/select_involved_roles", viewers: @function.authorized_viewer_ids, current_user_visibility_roles: [] %>
      <%= hidden_field_tag "function[authorized_viewers]", @function.authorized_viewers, :id => "authorized_viewers" %>
      <%= hidden_field_tag "current-role", @function.id %>
    </fieldset>
  </div>
</div>

<% if Redmine::Plugin.installed?(:redmine_comments) %>
  <div class="comments_tab">
    <h3><%= l(:functions_to_share_private_notes_with) %></h3>
    <div class="box tabular" id="private_notes">
      <fieldset>
        <p>
          <label><%= l(:text_private_notes_explanation) %></label>

          <% private_note_group_functions = PrivateNotesGroup.where(group_id: @function.id).map(&:function_id) %>

          <span style="display: inline-block;vertical-align: top;">
          <label class="block" style="padding-left:2em;">
          <%= radio_button_tag 'function[private_notes_group][]', 0, private_note_group_functions.empty?,
                               :id => 'role_all_functions_managed_on',
                               :data => { :disables => '.role_managed_function input' } %>
            <%= l(:label_can_share_private_note_with_all_roles) %>
          </label>
          <label class="block" style="padding-left:2em;">
            <%= radio_button_tag 'function[private_notes_group][]', 0, private_note_group_functions.present?,
                                 :id => 'role_all_functions_managed_off',
                                 :data => { :enables => '.role_managed_function input' } %>
            <%= l(:label_limit_private_note_visibility_to_these_roles) %>:
          </label>
          <span style="max-height: 300px;overflow: scroll;display: inline-block;">
            <% Function.sorted.where.not(id: @function.id).each do |f| %>
              <label class="block role_managed_function" style="padding-left:4em;cursor: pointer" title="<%= f.description %>">
                <%= check_box_tag 'function[private_notes_group][]', f.id, private_note_group_functions.include?(f.id), :id => nil %>
                <%= f.name %>
              </label>
            <% end %>
            <%= hidden_field_tag 'function[private_notes_group][]', '' %>
          </span>
        </span>

        </p>
      </fieldset>
    </div>
  </div>
  <%= javascript_tag do %>
    $(function() {
    if ((typeof $().select2) === 'function') {
    $('#function_private_notes_group').select2();
    }
    });
  <% end %>
<% end %>

app/views/functions/_function_issue.html.erb
<h3 class="title"><%= l(:label_functional_roles) %></h3>
<div>
  <% if @functions.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <table class="functions-table">
      <tr>
        <td class="main-column">
          <table class="list">
            <thead>
            <tr>
              <th><%= l(:field_name) %></th>
              <th><%= l(:field_description) %></th>
            </tr>
            </thead>
            <tbody>
            <% @functions.each do |function| %>
              <tr>
                <td>
                  <div class="involved-roles flex-container">
                    <% styles = viewers.include?(function.id.to_s) ? 'involved' : '' %>
                    <%= render "functions/visibility_role", function: function, styles: styles %>
                  </div>
                </td>
                <td>
                  <div class="flex-container">
                    <%= textilizable(function, :description) %>
                  </div>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </td>
      </tr>
      <tr>
        <td class="side-column">
          <table class="status-table">
            <tr>
              <%# Define style classes %>
              <% roles_status = [
                { label: :label_roles_selected_for_issue_with_members, style: 'disabled involved' },
                { label: :label_roles_selected_for_issue_without_members, style: 'disabled involved no-member' },
                { label: :label_roles_not_selected_for_issue_with_members, style: 'disabled' },
                { label: :label_roles_not_selected_for_issue_without_members, style: 'disabled no-member' }
              ] %>

              <% roles_status.each do |role| %>
                <td>
                  <div class="involved-roles flex-container">
                    <span class="role <%= role[:style] %>">
                      <span class="status-icon">
                        <i class="fa fa-check"></i><i class="fa fa-times"></i>
                      </span>
                      <i class="fa fa-lock"></i>
                    </span>
                  </div>
                </td>
                <td><%= l(role[:label]) %></td>
              <% end %>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  <% end %>
</div>

app/views/functions/_function_new_issue.html.erb
<h3 class="title"><%= l(:label_functional_roles) %></h3> 
<div> 
  <% if @functions.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
  <table style="width:100%;">
    <tr>
      <td style="width:75%;">
        <table class="list">
          <thead>
            <tr>
              <th><%= l(:field_name) %></th>
              <th><%= l(:field_description) %></th>
            </tr>
          </thead>            
          <% current_user_visibility_roles = functional_roles_for_current_user(@project)%>
          <% @functions.each do |function| %>
          <tr>
            <td>
              <div class='involved-roles' style='display: flex;'>
                 <span>             
                    <% styles = viewers.include?(function.id.to_s) ? 'involved ' : '' %>
                    <% styles << (current_user_visibility_roles.include?(function) ? ' mine' : '') %>
                    <%= render "functions/visibility_role", :function => function, :styles => styles %>
                </span>
              </div>
            </td>
            <td>
              <div  style='display: flex;'>
                <%= textilizable(function, :description) %>
              </div>
            </td>
            </tr>
          <% end %>
          </table>
        </td>      
    </tr>
    <tr>
    <td style="width:25%;">
      <table style="vertical-align: top;">
        <tr>
          <td>
            <div class='involved-roles' style='display: flex;'>
              <% styles = "disabled" + ( " involved" ) %>
              <span class="role <%= styles %>">
              <span class=status-icon><i class=fa-icon-ok></i><i class=fa-icon-remove></i></span>
                <i class="fa-icon-lock"></i>
              </span>               
            </div>
          </td>
          <td>
            <%= l(:label_roles_selected_for_issue_with_members) %>
          </td>                 
          <td>
            <div class='involved-roles' style='display: flex;'>
              <% styles = "disabled" + ( " involved" ) %>
              <span class="role <%= styles %> <%= 'no-member'%>">
              <span class=status-icon><i class=fa-icon-ok></i><i class=fa-icon-remove></i></span>
              <i class="fa-icon-lock"></i>
              </span>                
            </div>
          </td>
          <td>
            <%= l(:label_roles_selected_for_issue_without_members) %>
          </td>
          <td>
            <div class='involved-roles' style='display: flex;'>
              <% styles = "disabled" + ( " " ) %>
              <span class="role <%= styles %>">
              <span class=status-icon><i class=fa-icon-ok></i><i class=fa-icon-remove></i></span>
                <i class="fa-icon-lock"></i>
              </span>
            </div>
          </td>
          <td>
            <%= l(:label_roles_not_selected_for_issue_with_members) %>
          </td>                  
          <td>
            <div class='involved-roles' style='display: flex;'>
              <% styles = "disabled" + ( " " ) %>
              <span class="role <%= styles %> <%= 'no-member'%>">
              <span class=status-icon><i class=fa-icon-ok></i><i class=fa-icon-remove></i></span>
                <i class="fa-icon-lock"></i>
              </span>                
            </div>
          </td>
          <td>
            <%= l(:label_roles_not_selected_for_issue_without_members) %>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  </table>
  <% end %>
</div>

app/views/functions/_index.html.erb
<div style="margin-top: 25px;padding-top: 6px;">

  <div class="contextual">
    <%= link_to l(:label_role_new), new_function_path, :class => 'icon icon-add' %>
    <%= link_to l(:label_visibilities_report), visibilities_functions_path, :class => 'icon icon-summary' %>
  </div>

  <h2><%=l(:label_functional_roles)%></h2>

  <table class="list functional_roles">
    <thead>
      <tr>
        <th><%=l(:label_role)%></th>
        <th></th>
      </tr>
    </thead>
    <tbody>

    <% @functional_roles&.each do |role| %>
      <tr class="item">
        <td class="name"><%= content_tag('span', link_to(h(role.name), edit_function_path(role))) %></td>
        <td class="buttons">
          <%= reorder_handle(role) %>
          <%= delete_link function_path(role) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

</div>

<%= javascript_tag do %>
  $(function() { $("table.functional_roles tbody").positionedItems({items: ".item"}); });
<% end %>

app/views/functions/_select_involved_roles.html.erb
<%
   @project = @issue.project if @issue
   if @project.present?
     @functions = Function.available_functions_for(@project).sorted
   else
     @functions = Function.sorted
   end
   hidden_functions ||= []
   @users_by_function = @project.users_by_function if @project.present?
%>

<p id=involved-roles-form class=involved-roles>
  <label><%= l(:label_involved_members) %>
    <span style="margin-top:5px;margin-left:5px;">
      <% if @issue.present? %>
        <%= link_to l(:label_functional_roles),
              {:controller => 'functions', :action => 'index_issue', :project_id => @issue.project.id, :viewers => viewers.join(',')},
              :class => 'icon-only icon-help',
              :remote => true,
              :method => 'get' %>
      <% end %>
    </span>
  </label>
  <% (@functions-hidden_functions).each do |function| %>
    <% styles = viewers.include?(function.id) ? 'involved ' : '' %>
    <% styles << ' mine' if current_user_visibility_roles.include?(function) %>
    <%= render "functions/visibility_role", :function => function, :styles => styles %>
  <% end %>
  <% hidden_functions.each_with_index do |function, index| %>
    <%= link_to_function l('show_silent_roles'),
                         "$(this).closest('div').find('.hidden_function').toggle();toggle_name(this);return false;",
                         :class => 'toggle-hidden-functions',
                         :style => ''  if index==0  %>
    <%= '<BR>'.html_safe if index==0 %>
    <% styles = viewers.include?(function.id) ? 'involved ' : '' %>
    <% styles << ' mine' if current_user_visibility_roles.include?(function) %>
    <% styles << ' hidden_function' %>
    <%= render "functions/visibility_role", :function => function, :styles => styles %>
  <% end %>
</p>

<script>
  $('.hidden_function').hide();
  function toggle_name(lnk_obj){
    lnk_obj.innerHTML = (lnk_obj.innerHTML == '<%= l('hide_silent_roles') %>') ? '<%= l('show_silent_roles') %>' : '<%= l('hide_silent_roles') %>' ;
  }
</script>

app/views/functions/_visibility_role.html.erb
<% if @project.present? && @users_by_function.present?
     users_by_function = @users_by_function[function]
     users_names = users_by_function.blank? ? l(:label_no_member_has_this_role_in_this_project) : users_by_function.map(&:name).join(", ")
   end %>
<span class="role <%= styles %> <%= 'no-member' if @project.present? && users_by_function.blank? %>" data-role-id="<%= function.id %>" title="<%= users_names %>">
  <span class=status-icon><i class=fa-icon-ok></i><i class=fa-icon-remove></i></span>
  <%= function.name %>
  <i class="fa-icon-lock"></i>
</span>

app/views/functions/edit.html.erb
<%= title [l(:label_functional_roles), roles_path], @function.name %>

<%= labelled_form_for @function do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_save) %>
<% end %>

app/views/functions/index.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'functions/project_function', :locals => {:project => @project, :isuue => @isuue}) %>');
showModal('ajax-modal', '1200px');

app/views/functions/index_issue.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'functions/function_issue', :locals => {:project => @project, :viewers => @viewers}) %>');
showModal('ajax-modal', '1200px');

app/views/functions/index_new_issue.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'functions/function_new_issue', :locals => { :project => @project, :viewers => @viewers }) %>');
showModal('ajax-modal', '1500px');

app/views/functions/new.html.erb
<%= title [l(:label_functional_roles), roles_path], l(:label_role_new) %>

<%= labelled_form_for @function do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= submit_tag l(:button_create) %>
<% end %>

app/views/functions/visibilities.html.erb
<%= title [l(:label_role_plural), roles_path], l(:label_visibilities_report) %>

<%= form_tag visibilities_functions_path, :id => 'visibilities_form' do %>
  <%= hidden_field_tag 'visibilities[0]', '', :id => nil %>
  <div class="autoscroll">
    <table class="list visibilities">
      <thead>
      <tr>
        <th style="width: 200px;white-space: pre-line;vertical-align: middle;"><span>Rôle de l'auteur</span></th>
        <% @functional_roles.each do |function| %>
          <th style="width: 100px;white-space:pre-line;vertical-align: middle;">
            <%= content_tag('span', h(function.name)) %>
          </th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <% @functional_roles.each do |function| %>
        <tr visibility-<%= function.name.parameterize %>">
        <td class="name">
          <%= content_tag('span', h(function.name)) %>
        </td>
        <% @functional_roles.each do |column| %>
          <td>
            <%= check_box_tag "visibilities[#{function.id}][]", column.id, (function.authorized_viewer_ids.include?(column.id)), :id => nil, :class => "role-#{function.id}", disabled: function == column %>
          </td>
        <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <p><%= check_all_links 'visibilities_form' %></p>
  <p><%= submit_tag l(:button_save) %></p>
<% end %>