config/routes.rb
RedmineApp::Application.routes.draw do
  resources :functions, except: [:index, :show] do
    collection do
      match '/visibilities', to: "functions#visibilities", :via => [:get, :post]
      put '/available_functions_per_project', to: "functions#available_functions_per_project"
      put '/visible_functions_per_tracker', to: "functions#visible_functions_per_tracker"
      put '/activated_functions_per_tracker', to: "functions#activated_functions_per_tracker"
      put '/copy_functions_settings_from_project', to: "functions#copy_functions_settings_from_project"
    end
  end
  resources :functional_roles, only: [:update]  
  get 'issues/functions/:project_id(/*viewers)', :controller => 'functions', :action => 'index_issue' ,:as => 'index_issue_function'
end

app/models/function.rb
class Function < ApplicationRecord
  include Redmine::SafeAttributes

  acts_as_positioned

  safe_attributes :name, :position, :authorized_viewers, :move_to, :hidden_on_overview, :active_by_default, :see_all_issues, :description

  has_many :member_functions, :dependent => :destroy
  has_many :members, :through => :member_functions

  has_many :project_functions, :dependent => :destroy
  if Redmine::Plugin.installed?(:redmine_organizations)
    has_many :organization_functions, :dependent => :destroy
    has_many :organization_non_member_functions, :dependent => :destroy
  end
  has_many :projects, :through => :project_functions

  after_create :set_own_visibility,
               :if => Proc.new { |_| Function.column_names.include?("authorized_viewers") }

  validates_presence_of :name
  validates_length_of :name, maximum: 40

  scope :sorted, lambda { order("#{table_name}.position ASC") }
  scope :active_by_default, -> { where("active_by_default = ?", true) }
  scope :visible_on_project_overview, -> { where(hidden_on_overview: false) }

  def self.available_functions_for(project)
    functions = Function.joins(:project_functions).where("project_id = ?", project.id).sorted if project.present?
    if functions == nil || functions.blank?
      functions = Function.active_by_default.sorted
    end
    functions
  end

  def authorized_viewer_ids
    "#{authorized_viewers}".split("|").reject(&:blank?).map(&:to_i)
  end

  def to_s
    name
  end

  def allowed_to?(action)
    true # TODO Remove this method without breaking issues search
  end

  def users_by_project(project)
    User.joins(:members => :member_functions).where("function_id = ? AND project_id = ?", self.id, project.id).active.order("lastname ASC")
  end

  def users_by_project_and_organization(project, organization)
    User.joins(:members => :member_functions)
        .where("function_id = ?", self.id)
        .where("project_id = ?", project.id)
        .where("organization_id = ?", organization.id)
        .active.order("lastname ASC")
  end

  def self.functions_from_authorized_viewers(authorized_viewers)
    Function.where(:id => "#{authorized_viewers}".split("|")).sorted
  end

  def is_activated?(project:)
    project.functions.present? ? project.functions.include?(self) : self.active_by_default
  end

  def update_private_notes_group(functions_ids)
    grouped_functions = [self] | Function.where(id: functions_ids)
    grouped_functions.each do |group|
      PrivateNotesGroup.where(group_id: group.id).where("function_id NOT IN (?)", grouped_functions.map(&:id)).delete_all
      PrivateNotesGroup.where(function_id: group.id).where("group_id NOT IN (?)", grouped_functions.map(&:id)).delete_all
      (grouped_functions - [group]).each do |f|
        PrivateNotesGroup.find_or_create_by(group_id: group.id, function_id: f.id)
      end
    end
  end

  private

  def set_own_visibility
    reload
    if !authorized_viewers.present? || !authorized_viewers.split('|').include?(self.id)
      update_attribute(:authorized_viewers, "#{authorized_viewers.present? ? authorized_viewers : "|"}#{self.id}|")
    end
  end

end

app/views/principal_memberships/_memberships_functions.html.erb
<td class="functional_roles">
  <span class="member-<%= membership.id %>-roles"><%=h membership.functions.sort.uniq.collect(&:to_s).join(', ') %></span>
</td>

app/views/principal_memberships/_new_form.html.erb
<!-- begin untouched core view -->

<fieldset class="box">
  <legend><%= toggle_checkboxes_link('.projects-selection input:enabled') %><%= l(:label_project_plural) %></legend>
  <div class="objects-selection">
    <div class="projects-selection">
      <%= render_project_nested_lists(@projects) do |p| %>
        <label>
          <%= check_box_tag('membership[project_ids][]', p.id, false, :id => nil, :disabled => @principal.member_of?(p)) %> <%= p %>
        </label>
      <% end %>
    </div>
  </div>
</fieldset>

<fieldset class="box">
  <legend><%= toggle_checkboxes_link('.roles-selection input') %><%= l(:label_role_plural) %></legend>
  <div class="roles-selection">
    <% @roles.each do |role| %>
      <label>
        <%= check_box_tag 'membership[role_ids][]', role.id, false, :id => nil %>
        <%= role %>
      </label>
    <% end %>
  </div>
</fieldset>

<!-- end untouched core view -->

<!-- Adding here our functional roles -->

<% functions = Function.sorted.all %>
<fieldset class="box">
  <legend><%= l(:label_functional_roles) %></legend>
  <div class="functional-roles-selection two-columns">
    <% functions.each do |function| %>
      <div>
        <%= label_tag do %>
          <%= check_box_tag 'membership[function_ids][]', function.id, false, :id => nil %>
          <%= h(function) %>
        <% end %>
      </div>
    <% end %>
  </div>
</fieldset>

<!-- end of our addition -->