config/routes.rb
RedmineApp::Application.routes.draw do
  resources :functions, except: [:index, :show] do
    collection do
      match '/visibilities', to: "functions#visibilities", :via => [:get, :post]
      put '/available_functions_per_project', to: "functions#available_functions_per_project"
      put '/visible_functions_per_tracker', to: "functions#visible_functions_per_tracker"
      put '/activated_functions_per_tracker', to: "functions#activated_functions_per_tracker"
      put '/copy_functions_settings_from_project', to: "functions#copy_functions_settings_from_project"
    end
  end
  resources :functional_roles, only: [:update]  
  get 'issues/functions/:project_id(/*viewers)', :controller => 'functions', :action => 'index_issue' ,:as => 'index_issue_function'
end

app/views/projects/_functions_description.html.erb
<div class="modal" id="functions_description">
  <h3 class="title"><%= l(:label_functions_activated_description) %></h3>
  <% if functions.any? %>
    <dl>
      <% functions.each do |function| %>
        <dt><%= function.name %></dt>
        <dd><%= function.description %></dd>
      <% end %>
    </dl>
  <% else %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% end %>
</div>

app/views/projects/_members_box_by_function.html.erb
<% if !User.current.respond_to?(:can_see_detailed_project_homepage?) || User.current.can_see_detailed_project_homepage?(@project) %>

  <div class="members box">

    <h3>
      <%= l(:label_member_plural) %>
      <%= link_to l(:label_open_functions_activated_description), '#',
                  class: 'icon-only icon-help',
                  style: "margin-top: -3px;margin-left: 4px;",
                  title: l(:label_open_functions_activated_description),
                  onclick: "showModal('functions_description', '500px'); return false;" %>
    </h3>

    <%= render partial: 'projects/functions_description', locals: { functions: @project.functions.visible_on_project_overview.sorted } %>

    <% if Redmine::Plugin.installed?(:redmine_organizations) %>
      <% @users_by_function_and_organization = @project.users_by_function_and_organization %>
      <% if @users_by_function_and_organization.any? %>
        <p>
          <% @users_by_function_and_organization.keys.sort_by(&:position).each do |function| %>
          <div class="function">
            <div class="function_name" title="<%= function.description %>" style="cursor: pointer"><%= h function %></div>
            <div class="organizations">
              <% @users_by_function_and_organization[function].keys.sort_by(&:name).map do |org| %>
                <div class="organization">
                  <%= if org.new_record?
                        @users_by_function_and_organization[function][org].map { |u| link_to_user u }.join(", ").html_safe
                      else
                        link_to_organization(org, { :link_ancestors => false, :fullname => true }) +
                          content_tag(:span, " : #{@users_by_function_and_organization[function][org].map { |u| link_to_user u }.join(", ")}".html_safe,
                                      :class => "organization-members")
                      end.html_safe %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        </p>
      <% end %>
    <% end %>

  </div>

<% end %>

app/views/projects/_settings_functional_roles_tab.html.erb
<div class="limited_visibility_project_settings">

  <%= render 'projects/settings_functional_roles_tabs' %>

  <% case params[:nav] %>
  <% when 'defaults' %>
    <%= render 'projects/tab_selection_by_default' %>
  <% when 'silent' %>
    <%= render 'projects/tab_silent_functions' %>
  <% when 'init' %>
    <%= render 'projects/tab_copy_configuration' %>
  <% else %>
    <%= render 'projects/tab_activated_functions' %>
  <% end %>

</div>

app/views/projects/_settings_functional_roles_tabs.html.erb
<ul class="navigation">
  <li class="<%= "active" if params[:nav] == 'general' || params[:nav].blank? %>"><%= link_to l(:label_activated_roles), url_for(tab: 'functional_roles', nav: 'general') %></li>
  <li class="<%= "active" if params[:nav] == 'defaults' %>"><%= link_to l(:label_default_values), url_for(tab: 'functional_roles', nav: 'defaults') %></li>
  <li class="<%= "active" if params[:nav] == 'silent' %>"><%= link_to l(:label_silent_roles), url_for(tab: 'functional_roles', nav: 'silent') %></li>
  <li class="<%= "active" if params[:nav] == 'init' %>"><%= link_to l(:label_reset), url_for(tab: 'functional_roles', nav: 'init') %></li>
</ul>

app/views/projects/_tab_activated_functions.html.erb
<% @project.functions ||= Function.active_by_default %>
<% members_per_function = @project.members_per_function %>

<%= form_for(:functions,
             :method => :put,
             :url => {:controller => 'functions',
                      :action => 'available_functions_per_project',
                      :project_id => @project.id},
             :html => {:id => "functions-form"}) do %>

  <fieldset class="box">
    <h2><%= l(:text_select_project_functional_roles) %></h2>
    
    <ul style="list-style: none;">
      <p><%= check_all_links "functions-form" %></p>

      <% Function.sorted.each do |function| %>
        <% activated = function.is_activated?(project: @project) %>
        <li>
          <label title="<%= function.description %>" style="cursor: pointer">
            <%= check_box_tag 'function_ids[]', function.id, activated %>
            <%= "#{function.name}#{" (#{members_per_function[function.id].to_i} membres)"}" %>
          </label>
        </li>
      <% end %>
    </ul>

    <p><%= submit_tag l(:button_save) %></p>
  </fieldset>
<% end %>

<script type="text/javascript">
    $(function () {
        $('select#function_ids').select2({
            containerCss: {width: '600px', minwidth: '600px'},
            width: 'style'
        });
    });
</script>

app/views/projects/_tab_copy_configuration.html.erb
<%= form_for(:functions,
             :method => :put,
             :url => {:controller => 'functions',
                      :action => 'copy_functions_settings_from_project',
                      :project_id => @project.id,
                      :nav => 'init'
             }) do %>
  <h2 style="margin-top: 10px;"><%= l(:label_copy_settings_from_another_project)%></h2>
  <fieldset class="box">
    <p>
      <% projects = Project.active.where("id IN (?)", ProjectFunction.select(:project_id).group(:project_id).pluck(:project_id)).select(:id, :name, :identifier, :lft, :rgt).to_a
         projects -= [@project]
         if projects.any?
           options =
               ("<option value=''>#{l(:label_select_project)}</option>" +
                   '<option value="" disabled="disabled">---</option>').html_safe
           options << project_tree_options_for_select(projects) do |p|
             {:value => p.id}
           end
           options = options.gsub('&nbsp;&#187;', '&nbsp;').html_safe %>
        <%= select_tag :project_from, options %>
        <%= submit_tag l(:button_copy) %>
      <% else %>

      <p><%= l(:label_no_other_project_configured_for_moment)%></p>

    <% end %>

    </p>
  </fieldset>
<% end %>


<script type="text/javascript">
    $(function () {
        $('#project_from').select2({
            containerCss: {width: '300px', minwidth: '300px'},
            width: 'style'
        });
    });
</script>

app/views/projects/_tab_selection_by_default.html.erb
<h2 style="margin-top: 10px;"><%= l(:label_default_values) + " :" %></h2>

<%= form_for(:functions,
             :method => :put,
             :url => { controller: 'functions',
                       action: 'available_functions_per_project',
                       project_id: @project.id,
                       nav: 'defaults'
             },
             :html => { :id => "functions-form" }) do %>

  <fieldset class="box">
    <p>
      <label><%= l(:label_visibility_will_be_pre_filled_according)%></label>
      <%= select_tag :autocheck_mode, options_for_select({l(:label_of_role_of_user) => '1', l(:label_of_tracker_of_demand) => '2'}, @project.autochecked_functions_mode || '1') %>
    </p>
    <p><%= submit_tag l(:button_save) %></p>
  </fieldset>
<% end %>

<fieldset class="box">
  <%= form_for(:functions,
               :method => :put,
               :url => { controller: 'functions',
                         action: 'activated_functions_per_tracker',
                         project_id: @project.id,
                         nav: 'defaults'
               },
               :html => { :id => "autocheck-form" }) do %>
    <div class="autoscroll">
      <% functions = @project.functions.present? ? @project.functions.sorted : Function.active_by_default.sorted %>
      <table class="list visibilities" id="autocheck_functions_per_tracker">
        <thead>
        <tr>
          <th style="width: 200px;white-space: pre-line;vertical-align: middle;"></th>
          <% functions.each do |function| %>
            <th style="width: 100px;vertical-align: middle;text-align: center;">
              <%= content_tag('span', h(function.name)) %>
            </th>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% checked_functions_per_tracker = {}, {}
           @project.trackers.each { |t| checked_functions_per_tracker[t.id] = [] }
           ProjectFunctionTracker.joins(:project_function).includes(:project_function).where("project_id = ?", @project.id).each do |r|
             checked_functions_per_tracker[r.tracker_id] << r.project_function.function_id if checked_functions_per_tracker[r.tracker_id] && r.checked
           end
        %>
        <% @project.trackers.sorted.each do |tracker| %>
          <tr class="visibility-<%= tracker.name.parameterize %>">
            <td class="name">
              <%= content_tag('span', h(tracker.name)) %>
            </td>
            <% functions.each do |function| %>
              <td style="text-align: center;">
                <label style="display: block;" class="autocheck_checkbox">
                  <%= check_box_tag "function_activation_per_tracker[#{tracker.id}][]", function.id, (checked_functions_per_tracker[tracker.id].include?(function.id)), :id => nil, :class => "function-#{function.id}" %>
                  Coché
                </label>
              </td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>

      <table class="list visibilities" id="autocheck_functions_per_function">
        <% if @project.functions.empty? %>
          <p><%= l(:label_confirm_the_active_fuctional_roles_for_this_project_first)%></p>
        <% else %>
          <thead>
          <tr>
            <th style="width: 200px;white-space: pre-line;vertical-align: middle;"><%= l(:label_user_role)%></th>
            <% @project.functions.sorted.each do |function| %>
              <th style="width: 100px;vertical-align: middle;text-align: left;">
                <%= content_tag('span', h(function.name)) %>
              </th>
            <% end %>
          </tr>
          </thead>
          <tbody>
          <% checked_functions_per_user_functions = {}
             @project.functions.each { |t| checked_functions_per_user_functions[t.id] = [] }
             @project.project_functions.each do |pf|
               authorized_viewer_ids = pf.authorized_viewer_ids.present? ? pf.authorized_viewer_ids : pf.function.authorized_viewer_ids
               authorized_viewer_ids.each do |function_id|
                 checked_functions_per_user_functions[pf.function_id] << function_id if checked_functions_per_user_functions[pf.function_id] && function_id.present?
               end
             end
          %>
          <% @project.functions.sorted.each do |row_function| %>
            <tr class="visibility-<%= row_function.name.parameterize %>">
              <td class="name">
                <%= content_tag('span', h(row_function.name), :title => row_function.description, :style =>"cursor: pointer") %>
              </td>
              <% @project.functions.sorted.each do |col_function| %>
                <td style="text-align: left;">
                  <label style="display: block;" class="autocheck_checkbox">
                    <%= check_box_tag "function_activation_per_user_function[#{row_function.id}][]", col_function.id, (checked_functions_per_user_functions[row_function.id].include?(col_function.id)), :id => nil, :class => "function-#{col_function.id}" %>
                    Coché
                  </label>
                </td>
              <% end %>
            </tr>
          <% end %>
          </tbody>
        <% end %>
      </table>
    </div>
    <p><%= check_all_links 'autocheck-form' %></p>
    <p><%= submit_tag l(:button_save) %></p>
  <% end %>

</fieldset>

app/views/projects/_tab_silent_functions.html.erb
<h2 style="margin-top: 10px;"><%= l(:label_silent_roles_by_tracker) %></h2>
<fieldset class="box">
  <% if @project.functions.empty? %>
    <p><%= l(:label_confirm_the_active_fuctional_roles_for_this_project_first)%></p>
  <% else %>

    <%= form_for(:functions,
                 :method => :put,
                 :url => {controller: 'functions',
                          action: 'visible_functions_per_tracker',
                          project_id: @project.id,
                          nav: 'silent'
                 },
                 :html => {:id => "visibilities-form"}) do %>
      <div class="autoscroll">
        <table class="list visibilities">
          <thead>
          <tr>
            <th style="width: 200px;vertical-align: middle;"></th>
            <% @project.trackers.sorted.each do |function| %>
              <th style="width: 100px;vertical-align: middle;text-align: left;">
                <%= content_tag('span', h(function.name)) %>
              </th>
            <% end %>
          </tr>
          </thead>
          <tbody>
          <% visible_functions_per_tracker = {}
            @Pro_Func_tracker = ProjectFunctionTracker.joins(:project_function).includes(:project_function).where("project_id = ?", @project.id)            
            if @Pro_Func_tracker.count > 0
              @project.trackers.each { |t| visible_functions_per_tracker[t.id] = []; }             
              @Pro_Func_tracker.each do |r|
                visible_functions_per_tracker[r.tracker_id] << r.project_function.function_id if visible_functions_per_tracker[r.tracker_id] && r.visible
             end
            end            
          %>
          <% functions = @project.functions.present? ? @project.functions : Function.active_by_default %>
          <% functions.sorted.each do |function| %>
            <tr class="visibility-<%= function.name.parameterize %>">
              <td class="name">
                <%= content_tag('span', h(function.name), :title => function.description, :style =>"cursor: pointer") %>
              </td>
              <% @project.trackers.sorted.each do |tracker| %>
                <td style="text-align: left;">
                  <label>
                    <%= check_box_tag "function_visibility[#{tracker.id}][]", function.id, (visible_functions_per_tracker.empty? || visible_functions_per_tracker[tracker.id].include?(function.id) ), :id => nil, :class => "function-#{function.id}" %>
                    Visible
                  </label>
                </td>
              <% end %>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <p><%= check_all_links 'visibilities-form' %></p>
      <p><%= submit_tag l(:button_save) %></p>
    <% end %>
  <% end %>

</fieldset>

app/views/projects/_visibility.html.erb
<%= error_messages_for 'member' %>
<% roles = Role.visibility_roles.all
   members = @project.member_principals.sort_by{ |x| x.principal.lastname.downcase } %>

<div>
  <% if members.any? %>
    <table class="list members">
      <thead><tr>
        <th><%= l(:label_user) %> / <%= l(:label_group) %></th>
        <th><%= l(:label_visibility_by_role) %></th>
        <th></th>
      </tr></thead>
      <tbody>
      <% members.each do |member| %>
        <% next if member.new_record? %>
        <tr id="member-<%= member.id %>" class="<%= cycle 'odd', 'even' %> member">
          <td class="<%= member.principal.class.name.downcase %>"><%= link_to_user member.principal %></td>
          <td class="roles">
            <span id="member-<%= member.id %>-roles">
              <% if member.roles.visibility_roles.all.present? %>
                <%= h member.roles.visibility_roles.sorted.pluck(:name).join(', ') %>
              <% else %>
                <span class="see_everything"><%= l('see_everything') %></span>
              <% end %>
            </span>
            <%= form_for(member, {:as => :membership, :remote => true, :url => update_visibility_roles_path,
                                  :method => :put,
                                  :html => { :id => "member-#{member.id}-roles-form", :class => 'hol' }}
                ) do |f| %>
              <p><% roles.each do |role| %>
                  <label>
                    <%= check_box_tag 'membership[role_ids][]', role.id, member.roles.include?(role) || (member.roles & roles).empty?,
                                           :disabled => member.member_roles.detect { |mr| mr.role_id == role.id && !mr.inherited_from.nil?} %> <%=h role %>
                  </label><br />
                <% end %>
              </p>
              <%= hidden_field_tag 'id', member.id %>
              <%= hidden_field_tag 'membership[role_ids][]', '' %>
              <p><%= submit_tag l(:button_change), :class => "small" %>
                <%= link_to_function l(:button_cancel),
                                     "$('#member-#{member.id}-roles').show(); $('#member-#{member.id}-roles-form').hide(); return false;"
                %></p>
            <% end %>
          </td>
          <td class="buttons" style="text-align: right;">
            <%= link_to_function l(:button_edit),
                                 "$('#member-#{member.id}-roles').toggle(); $('#member-#{member.id}-roles-form').toggle(); return false;",
                                 :class => 'icon icon-edit' %>
          </td>
          <%= call_hook(:view_projects_settings_members_table_row, { project: @project, member: member}) %>
        </tr>
      <% end; reset_cycle %>
      </tbody>
    </table>
  <% else %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% end %>
</div>