config/routes.rb
RedmineApp::Application.routes.draw do
  resources :functions, except: [:index, :show] do
    collection do
      match '/visibilities', to: "functions#visibilities", :via => [:get, :post]
      put '/available_functions_per_project', to: "functions#available_functions_per_project"
      put '/visible_functions_per_tracker', to: "functions#visible_functions_per_tracker"
      put '/activated_functions_per_tracker', to: "functions#activated_functions_per_tracker"
      put '/copy_functions_settings_from_project', to: "functions#copy_functions_settings_from_project"
    end
  end
  resources :functional_roles, only: [:update]  
  get 'issues/functions/:project_id(/*viewers)', :controller => 'functions', :action => 'index_issue' ,:as => 'index_issue_function'
end

app/views/roles/_managed_roles_and_functions.html.erb
<p class="manage_members_shown">
  <label><%= l(:label_member_management) %></label>

  <span style="display: inline-block;vertical-align: top;margin-right: 2em;">
    <label class="block">
    <%= radio_button_tag 'role[all_roles_managed]', 1, @role.all_roles_managed?, :id => 'role_all_roles_managed_on',
                         :data => {:disables => '.role_managed_role input'} %>
      <%= l(:label_member_management_all_roles) %>
    </label>
    <label class="block">
      <%= radio_button_tag 'role[all_roles_managed]', 0, !@role.all_roles_managed?, :id => 'role_all_roles_managed_off',
                           :data => {:enables => '.role_managed_role input'} %>
      <%= l(:label_member_management_selected_roles_only) %>:
    </label>

    <% Role.givable.sorted.each do |role| %>
      <label class="block role_managed_role" style="padding-left:2em;">
        <%= check_box_tag 'role[managed_role_ids][]', role.id, @role.managed_roles.to_a.include?(role), :id => nil %>
        <%= role.name %>
      </label>
    <% end %>
    <%= hidden_field_tag 'role[managed_role_ids][]', '' %>
  </span>

  <span style="display: inline-block;vertical-align: top;">
    <label class="block">
      <%= hidden_field_tag 'role[functions_managed]', false %>
      <%= check_box_tag 'role[functions_managed]', 1, @role.functions_managed?, :id => 'role_functions_managed_checkbox',
                        :data => {:enables => '#role_all_functions_managed_on, #role_all_functions_managed_off, .role_managed_function input'} %>
      <%= l(:label_member_management_functions) %>
    </label>
    <label class="block" style="padding-left:2em;">
    <%= radio_button_tag 'role[all_functions_managed]', 1, @role.all_functions_managed?, :id => 'role_all_functions_managed_on',
                         :data => {:disables => '.role_managed_function input'} %>
      <%= l(:label_member_management_all_functions) %>
    </label>
    <label class="block" style="padding-left:2em;">
      <%= radio_button_tag 'role[all_functions_managed]', 0, !@role.all_functions_managed?, :id => 'role_all_functions_managed_off',
                           :data => {:enables => '.role_managed_function input'} %>
      <%= l(:label_member_management_selected_functions_only) %>:
    </label>
    <span style="max-height: 300px;overflow: scroll;display: inline-block;">
      <% Function.sorted.each do |function| %>
        <label class="block role_managed_function" style="padding-left:4em;">
          <%= check_box_tag 'role[managed_function_ids][]', function.id, @role.managed_functions.to_a.include?(function), :id => nil %>
          <%= function.name %>
        </label>
      <% end %>
      <%= hidden_field_tag 'role[managed_function_ids][]', '' %>
    </span>
  </span>

  <br>

  <% if Redmine::Plugin.installed?(:redmine_organizations) %>
    <label><%= l(:label_organizations_management) %></label>
    <span style="display: inline-block;vertical-align: top;margin-right: 2em;">
      <label class="block">
      <%= radio_button_tag 'role[all_organizations_managed]', 1, @role.all_organizations_managed?, :id => 'role_all_organizations_managed_on',
                           :data => {:disables => '.role_managed_organization input'} %>
        <%= l(:label_organizations_management_all_organizations) %>
      </label>
      <label class="block">
        <%= radio_button_tag 'role[all_organizations_managed]', 0, !@role.all_organizations_managed?, :id => 'role_all_organizations_managed_off',
                             :data => {:enables => '.role_managed_organization input'} %>
        <%= l(:label_organizations_management_current_organization_only) %>
      </label>
    </span>
  <% end %>

</p>

app/views/roles/_visibility_role.html.erb
<span class="role <%= styles %>" data-role-id="<%= role.id %>">
  <span class=status-icon><i class=fa-icon-ok></i><i class=fa-icon-remove></i></span>
  <%= role.name %>
  <i class="fa-icon-lock"></i>
</span>

app/views/roles/visibilities.html.erb
<%= title [l(:label_role_plural), roles_path], l(:label_visibilities_report) %>

<%= form_tag(roles_visibilities_report_path, :id => 'visibilities_form') do %>
<%= hidden_field_tag 'visibilities[0]', '', :id => nil %>
<div class="autoscroll">
<table class="list visibilities">
<thead>
    <tr>
      <th style="width: 200px;white-space: pre-line;vertical-align: middle;"><span>Rôle de l'auteur</span></th>
      <% @roles.each do |role| %>
        <th style="width: 100px;white-space:pre-line;vertical-align: middle;">
          <%= content_tag(role.builtin? ? 'em' : 'span', h(role.name)) %>
        </th>
      <% end %>
    </tr>
</thead>
<tbody>
<% @roles.each do |role| %>
  <tr class="<%= cycle('odd', 'even') %> visibility-<%= role.name.parameterize %>">
    <td class="name">
      <%= content_tag(role.builtin? ? 'em' : 'span', h(role.name)) %>
    </td>
    <% @roles.each do |column| %>
      <td>
        <%= check_box_tag "visibilities[#{role.id}][]", column.id, (role.authorized_viewer_ids.include?(column.id)), :id => nil, :class => "role-#{role.id}", disabled: role==column %>
      </td>
    <% end %>
  </tr>
<% end %>
</tbody>
</table>
</div>
<p><%= submit_tag l(:button_save) %></p>
<% end %>